Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

   config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
   config.vm.network "private_network", type: "dhcp"
   config.vm.synced_folder "../data", "/vagrant_data"

   config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
       vb.gui = true
       vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
       vb.customize ["modifyvm", :id, "--vram", "32"]
  # Customize the amount of memory on the VM:
        vb.memory = "2048"
        vb.cpus ="2"
   end

  config.vm.provision "file", source: '../files/.gitconfig', destination: '~/.gitconfig'
  config.vm.provision "shell", path: "../provisioners/install-gui-support.sh"
  config.vm.provision "shell", path: "../provisioners/install-java8.sh"
  config.vm.provision "shell", path: "../provisioners/install-maven.sh"
  config.vm.provision "shell", path: "../provisioners/install-git.sh"
  config.vm.provision "shell", path: "../provisioners/install-ngx.sh"
  config.vm.provision "shell", path: "../provisioners/install-node.sh"
  config.vm.provision "shell", path: "../provisioners/install-eclipse.sh"
  config.vm.provision "shell", path: "../provisioners/install-mongo.sh"
  config.vm.provision "shell", path: "../provisioners/install-docker.sh"
end